name: Gitub Actions test
  
on: 
      pull_request:
        branches: [main]
        
jobs: 
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
         go-version: '1.16.1' # The Go version to download (if necessary) and use.
      - name: Run vet & lint
        run: |
          go vet .
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
            # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
            version: v1.29  
      - name: Test
        run: go test -v ./...     
      - run: go run main.go
